# Generated by Django 4.2.5 on 2023-09-12 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리 명칭')),
                ('description', models.TextField(blank=True, null=True, verbose_name='카테고리 설명')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, verbose_name='아이디')),
                ('username', models.CharField(max_length=50, verbose_name='이름')),
                ('email', models.EmailField(default='example@example.com', max_length=254, unique=True, verbose_name='이메일')),
                ('password', models.CharField(max_length=100, verbose_name='비밀번호')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='수정일')),
                ('img', models.ImageField(upload_to='', verbose_name='이미지 파일')),
                ('tag', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='app.tag', verbose_name='태그')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
