# Generated by Django 4.2.5 on 2023-09-13 01:57

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_remove_post_tag_post_tags_alter_post_img_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="topic",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=100, verbose_name="주제"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="views",
            field=models.IntegerField(default=0, verbose_name="조회수"),
        ),
    ]
