# Generated by Django 4.2.5 on 2023-09-13 05:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_mymodel_post_topic_post_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="board_text",
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
